FROM public.ecr.aws/lambda/python:3.12


COPY requirements.txt ${LAMBDA_TASK_ROOT}
COPY build_model.py ${LAMBDA_TASK_ROOT}
COPY app.py ${LAMBDA_TASK_ROOT}

RUN pip install -r requirements.txt

RUN python build_model.py

CMD [ "lambda_function.handler" ] 